---
pagetitle: Teachings

format:
  html:
    css: ../assets/style_personalized.css
---

## Courses

#### [Probability and Stochastic Calculus](https://edu.epfl.ch/coursebook/en/probability-and-stochastic-calculus-FIN-415)

*EPFL*<br>
*Fall 2024*, TA as PhD student

This course gives an introduction to probability theory and stochastic calculus in discrete and continuous time. The fundamental notions and techniques introduced in this course have many applications in finance, for example for option pricing, risk management and optimal portfolio choice.



#### [Applied Systems Engineering](https://www.kth.se/student/kurser/kurs/SF2866?l=en)

*KTH Royal Institute of Technology*<br>
*Fall 2023*, TA as graduate student

The course contents will mainly be based on the following areas:

- Queueing models based on Markov processes, including models for queueing networks.
- Models for inventory optimization, deterministic as well as stochastic.
- Scheduling methods for production systems and transport systems, and route planning