---
title: "Optimizing wave energy converters: A co-design approach using surrogate modeling"
date: '2024-09-10'
author:
- name: Andrea Ruglioni
  orcid: 0009-0003-5208-5907
- name: Edoardo Pasta
  orcid: 0000-0001-9525-6284
- name: Nicolàs Faedo
  orcid: 0000-0002-7455-9558
- name: Paolo Brandimarte
  orcid: 0000-0002-6533-3055

categories:
  - Wave energy converters
  - Optimal co-design
  - Surrogate modeling
  - Deep kernel learning
  
subtitle: "A joint optimization of the physical structure and control system of wave energy converters using deep kernel learning as a surrogate model"
---

## Abstract

Wave energy converters (WECs) offer a promising source of renewable energy, but they require a careful joint optimization of both their geometry andcontrol strategy in order to cope with the complexity of marine environments.
This joint optimization process is hindered by high computational costs.
This paper presents an integrated co-design framework that simultaneously optimizes the WEC physical structure and control system using deep kernel learning (DKL) as a surrogate model.
The DKL model, trained on high-fidelity simulations, enables efficient and accurate predictions, while maintaining essential physical constraints.
A case study on a spherical WEC shows significant improvements in computational efficiency and a suitable prediction accuracy, advancing WEC design methodologies.